### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ChaiBapchya**
Capitalizations and word changes

### CODE REVIEW

**Comment by drjwbaker** [comment]
@thomasgpadilla Care to comment. My sense was that using lower case is a deliberate part of the sourcecaster look and feel. Right?

**Comment by ChaiBapchya** [comment]
Oh alright. Regardless, there were few changes in the use of words to make it readable.

**Comment by thomasgpadilla** [comment]
@drjwbaker yes, mostly style and feel but suggestions are always welcome!

**Comment by drjwbaker** [comment]
Thanks for the suggestions @ChaiBapchya I've integrated them at https://github.com/datapraxis/sourcecaster/commit/c22070a01b16996338dc46f0d3bfced7621eb0e2

**Comment by ChaiBapchya** [comment]
Alright.

**Pull request closed without merging**
